### ISSUE TITLE
Streams-HbaseSample.ipynb - job fails with Exception at runtime

### ISSUE THREAD

**Issue by markheger** [IBMStreams/sample.starter_notebooks#14]
```
Operator Name: HBASEPut
Exception in thread "Thread-9" java.lang.Exception: Expected attribute Timestamp to be present, but not found
	at com.ibm.streamsx.hbase.HBASEOperator.checkAndGetIndex(HBASEOperator.java:245)
	at com.ibm.streamsx.hbase.HBASEOperator.checkAndGetIndex(HBASEOperator.java:307)
	at com.ibm.streamsx.hbase.HBASEPut.initialize(HBASEPut.java:269)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:745)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:277)
sh: /home/streamsapp/.streams/pes/153: Is a directory
```

**Comment by markheger** [comment]
extend schema with `int64 Timestamp`
